spring:
  datasource:
    url: jdbc:mariadb://192.168.0.176:3306/syncle?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: nullpointer
    password: nullpointer

  mail:
    password: jzxh jwrw htzj wjvt

app:
  jwt:
    secret: 652be27da4a34843c65c18896a85d4c5323195904dfaed6b68ab8b71c3a85673

  google:
    client-id: 87398497046-84oro5ng2u5voe58rl92sm6u4f2vldv0.apps.googleusercontent.com